### ISSUE TITLE
it has been updated with a new wildcard

### ISSUE THREAD

**Issue by flybirdxx** [Kinglord/ComfyUI_Prompt_Gallery#4]
![image](https://github.com/user-attachments/assets/c5449a49-abd2-41c7-beab-4dfe85384836)
![image](https://github.com/user-attachments/assets/d72ba8c1-5c21-48c4-b9ef-cfbed6478db1)

First of all, thank you for your contribution, I think it is very good to use, I found that it has been updated with a new wildcard, because I don't know much about the code, although I simply add this new one from the code so that it can be read normally, but I hope you can update it to add it, thank you very much!

**Comment by Kinglord** [comment]
Cheers, glad you're enjoying it!

I actually added the Jobs wildcards last night when I did the last round of updates to get to v1.0. If I am a little slow anything released by navimixu you should be able to just add to that yamlFile declaration section you found and the rest of the code will pick everything up. 

In any case, if you update to the latest version you should see jobs in there without having to do any work 😁 - if you're not seeing it after an update let me know.

**Comment by Kinglord** [comment]
Closing this out since this is natively supported now and I haven't heard back on any issues. 😄
